name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
    env:
      CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
      CHATWORK_API_TOKEN: ${{ secrets.CHATWORK_API_TOKEN }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          roomId: ${{ secrets.CHATWORK_ROOM_ID }}
          token: ${{ secrets.CHATWORK_API_TOKEN }}
          mapping: |
            {
              "mechiru": "chatwork/mechiru"
            }
          context: |
            {
              "token": "***",
              "job": "notify",
              "ref": "refs/heads/master",
              "sha": "f8f9aca004ff0d2f29b0b4119fc09820b058849e",
              "repository": "mechiru/try-github-actions",
              "repository_owner": "mechiru",
              "repositoryUrl": "git://github.com/mechiru/try-github-actions.git",
              "run_id": "296984975",
              "run_number": "48",
              "retention_days": "90",
              "actor": "mechiru",
              "workflow": "notify",
              "head_ref": "",
              "base_ref": "",
              "event_name": "issues",
              "event": {
                "action": "opened",
                "issue": {
                  "active_lock_reason": null,
                  "assignee": {
                    "avatar_url": "https://avatars0.githubusercontent.com/u/46036584?v=4",
                    "events_url": "https://api.github.com/users/mechiru/events{/privacy}",
                    "followers_url": "https://api.github.com/users/mechiru/followers",
                    "following_url": "https://api.github.com/users/mechiru/following{/other_user}",
                    "gists_url": "https://api.github.com/users/mechiru/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/mechiru",
                    "id": 46036584,
                    "login": "mechiru",
                    "node_id": "MDQ6VXNlcjQ2MDM2NTg0",
                    "organizations_url": "https://api.github.com/users/mechiru/orgs",
                    "received_events_url": "https://api.github.com/users/mechiru/received_events",
                    "repos_url": "https://api.github.com/users/mechiru/repos",
                    "site_admin": false,
                    "starred_url": "https://api.github.com/users/mechiru/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/mechiru/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/mechiru"
                  },
                  "assignees": [
                    {
                      "avatar_url": "https://avatars0.githubusercontent.com/u/46036584?v=4",
                      "events_url": "https://api.github.com/users/mechiru/events{/privacy}",
                      "followers_url": "https://api.github.com/users/mechiru/followers",
                      "following_url": "https://api.github.com/users/mechiru/following{/other_user}",
                      "gists_url": "https://api.github.com/users/mechiru/gists{/gist_id}",
                      "gravatar_id": "",
                      "html_url": "https://github.com/mechiru",
                      "id": 46036584,
                      "login": "mechiru",
                      "node_id": "MDQ6VXNlcjQ2MDM2NTg0",
                      "organizations_url": "https://api.github.com/users/mechiru/orgs",
                      "received_events_url": "https://api.github.com/users/mechiru/received_events",
                      "repos_url": "https://api.github.com/users/mechiru/repos",
                      "site_admin": false,
                      "starred_url": "https://api.github.com/users/mechiru/starred{/owner}{/repo}",
                      "subscriptions_url": "https://api.github.com/users/mechiru/subscriptions",
                      "type": "User",
                      "url": "https://api.github.com/users/mechiru"
                    }
                  ],
                  "author_association": "OWNER",
                  "body": "@mechiru fuga",
                  "closed_at": null,
                  "comments": 0,
                  "comments_url": "https://api.github.com/repos/mechiru/try-github-actions/issues/15/comments",
                  "created_at": "2020-10-09T07:10:07Z",
                  "events_url": "https://api.github.com/repos/mechiru/try-github-actions/issues/15/events",
                  "html_url": "https://github.com/mechiru/try-github-actions/issues/15",
                  "id": 717912516,
                  "labels": [],
                  "labels_url": "https://api.github.com/repos/mechiru/try-github-actions/issues/15/labels{/name}",
                  "locked": false,
                  "milestone": null,
                  "node_id": "MDU6SXNzdWU3MTc5MTI1MTY=",
                  "number": 15,
                  "performed_via_github_app": null,
                  "repository_url": "https://api.github.com/repos/mechiru/try-github-actions",
                  "state": "open",
                  "title": "hoge",
                  "teams_url": "https://api.github.com/repos/mechiru/try-github-actions/teams",
                  "trees_url": "https://api.github.com/repos/mechiru/try-github-actions/git/trees{/sha}",
                  "updated_at": "2020-10-08T23:52:00Z",
                  "url": "https://api.github.com/repos/mechiru/try-github-actions",
                  "watchers": 0,
                  "watchers_count": 0
                },
                "sender": {
                  "avatar_url": "https://avatars0.githubusercontent.com/u/46036584?v=4",
                  "events_url": "https://api.github.com/users/mechiru/events{/privacy}",
                  "followers_url": "https://api.github.com/users/mechiru/followers",
                  "following_url": "https://api.github.com/users/mechiru/following{/other_user}",
                  "gists_url": "https://api.github.com/users/mechiru/gists{/gist_id}",
                  "gravatar_id": "",
                  "html_url": "https://github.com/mechiru",
                  "id": 46036584,
                  "login": "mechiru",
                  "node_id": "MDQ6VXNlcjQ2MDM2NTg0",
                  "organizations_url": "https://api.github.com/users/mechiru/orgs",
                  "received_events_url": "https://api.github.com/users/mechiru/received_events",
                  "repos_url": "https://api.github.com/users/mechiru/repos",
                  "site_admin": false,
                  "starred_url": "https://api.github.com/users/mechiru/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/mechiru/subscriptions",
                  "type": "User",
                  "url": "https://api.github.com/users/mechiru"
                }
              },
              "server_url": "https://github.com",
              "api_url": "https://api.github.com",
              "graphql_url": "https://api.github.com/graphql",
              "workspace": "/home/runner/work/try-github-actions/try-github-actions",
              "action": "self",
              "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
              "path": "/home/runner/work/_temp/_runner_file_commands/add_path_4fdc7afd-4961-45e4-8449-72a8508c4875",
              "env": "/home/runner/work/_temp/_runner_file_commands/set_env_4fdc7afd-4961-45e4-8449-72a8508c4875"
            }
